### ISSUE TITLE
Filter box stopped working

### ISSUE THREAD

**Issue by ddrscott** [ddrscott/golumnpy#8]
```
04:31:03 AM: Debug: filtered count: 66,176
Traceback (most recent call last):
  File "golumn/App.py", line 153, in on_filter_key
    self.grid.fuzzy_filter(like=self.search.Value + '%')
  File "golumn/SQLiteGrid.py", line 108, in fuzzy_filter
    self.GetTable().fuzzy_filter(*args, **kw)
  File "golumn/SQLiteTable.py", line 286, in fuzzy_filter
    self.apply_query()
  File "golumn/SQLiteTable.py", line 269, in apply_query
    grid.ProcessTableMessage(wx.grid.GridTableMessage(self, wx.grid.GRIDTABLE_NOTIFY_ROWS_DELETED, new_total + 1, self.total_rows - new_total))
wx._core.wxAssertionError: C++ assertion "nIndex + nRemove <= m_nCount" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py27/Phoenix/ext/wxWidgets/src/common/dynarray.cpp(379) in RemoveAt(): removing too many elements in wxArray::RemoveAt
```

**Comment by ddrscott** [comment]
It's working again. Not sure which commit. Sorry.
